name: "Build"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: nix-community
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build
